version: 2.1
jobs:
  build:
    working_directory: ~/jsonplaceholder
    docker:
      - image: circleci/node:10.15.3
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: start_server
          command: npm run start
          background: true
      - run:
          name: test
          command: npm run test_paschal
      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
